window.COMPANY_CATALOG = [
  { segment: 'MBB & consulting', name: 'BCG', url: 'https://careers.bcg.com/' },
  { segment: 'MBB & consulting', name: 'BCG Expand', url: 'https://careers.bcg.com/global/en/teams/expand' },
  { segment: 'MBB & consulting', name: 'McKinsey', url: 'https://www.mckinsey.com/careers/search-jobs' },
  { segment: 'MBB & consulting', name: 'Bain / Capability Network', url: 'https://www.bain.com/careers/' },
  { segment: 'MBB & consulting', name: 'Kearney', url: 'https://www.kearney.com/careers' },
  { segment: 'MBB & consulting', name: 'Alvarez & Marsal', url: 'https://www.alvarezandmarsal.com/careers' },
  { segment: 'MBB & consulting', name: 'ZS', url: 'https://www.zs.com/careers' },
  { segment: 'Foreign banks & GCCs', name: 'JPMorgan', url: 'https://www.jpmorganchase.com/careers' },
  { segment: 'Foreign banks & GCCs', name: 'Goldman Sachs', url: 'https://www.goldmansachs.com/careers' },
  { segment: 'Foreign banks & GCCs', name: 'Morgan Stanley', url: 'https://www.morganstanley.com/people-opportunities' },
  { segment: 'Foreign banks & GCCs', name: 'Bank of America', url: 'https://careers.bankofamerica.com/' },
  { segment: 'Foreign banks & GCCs', name: 'Citi', url: 'https://jobs.citi.com/' },
  { segment: 'Foreign banks & GCCs', name: 'Deutsche Bank', url: 'https://careers.db.com/' },
  { segment: 'Foreign banks & GCCs', name: 'Barclays', url: 'https://home.barclays/careers/' },
  { segment: 'Foreign banks & GCCs', name: 'HSBC', url: 'https://www.hsbc.com/careers' },
  { segment: 'Foreign banks & GCCs', name: 'NatWest', url: 'https://jobs.natwestgroup.com/' },
  { segment: 'Foreign banks & GCCs', name: 'Wells Fargo', url: 'https://www.wellsfargojobs.com/' },
  { segment: 'Foreign banks & GCCs', name: 'American Express', url: 'https://www.americanexpress.com/en-us/careers/' },
  { segment: 'Foreign banks & GCCs', name: 'State Street', url: 'https://careers.statestreet.com/' },
  { segment: 'Foreign banks & GCCs', name: 'Northern Trust', url: 'https://www.northerntrust.com/careers' },
  { segment: 'Foreign banks & GCCs', name: 'BNY', url: 'https://www.bny.com/corporate/global/en/careers.html' },
  { segment: 'Foreign banks & GCCs', name: 'Mastercard', url: 'https://www.mastercard.com/global/en/vision/corp-culture/our-people.html' },
  { segment: 'Foreign banks & GCCs', name: 'Visa', url: 'https://corporate.visa.com/en/careers.html' },
  { segment: 'Data, ratings & indices', name: 'S&P Global', url: 'https://www.spglobal.com/en/careers' },
  { segment: 'Data, ratings & indices', name: "Moody's", url: 'https://careers.moodys.com/' },
  { segment: 'Data, ratings & indices', name: 'MSCI', url: 'https://www.msci.com/careers' },
  { segment: 'Data, ratings & indices', name: 'FactSet', url: 'https://www.factset.com/careers' },
  { segment: 'Data, ratings & indices', name: 'Morningstar', url: 'https://www.morningstar.com/company/careers' },
  { segment: 'Data, ratings & indices', name: 'CRISIL', url: 'https://www.crisil.com/en/home/careers.html' },
  { segment: 'Data, ratings & indices', name: 'ICRA', url: 'https://www.icra.in/Careers' },
  { segment: 'Data, ratings & indices', name: 'CARE Ratings', url: 'https://www.careratings.com/careers' },
  { segment: 'Data, ratings & indices', name: 'Bloomberg', url: 'https://www.bloomberg.com/company/careers/' },
  { segment: 'Research KPOs', name: 'TresVista', url: 'https://www.tresvista.com/careers/' },
  { segment: 'Research KPOs', name: 'The Smart Cube', url: 'https://www.thesmartcube.com/careers' },
  { segment: 'Research KPOs', name: 'Evalueserve', url: 'https://www.evalueserve.com/careers/' },
  { segment: 'Research KPOs', name: 'Acuity Knowledge Partners', url: 'https://www.acuitykp.com/careers/' },
  { segment: 'Research KPOs', name: 'SG Analytics', url: 'https://www.sganalytics.com/careers/' },
  { segment: 'Big 4 & advisory', name: 'Deloitte USI', url: 'https://jobs.deloitte.com/' },
  { segment: 'Big 4 & advisory', name: 'EY GDS', url: 'https://www.ey.com/en_in/careers' },
  { segment: 'Big 4 & advisory', name: 'KPMG India', url: 'https://kpmg.com/in/en/home/careers.html' },
  { segment: 'Big 4 & advisory', name: 'PwC SDC', url: 'https://www.pwc.in/careers.html' },
  { segment: 'Big 4 & advisory', name: 'GT Bharat', url: 'https://www.grantthornton.in/careers/' },
  { segment: 'Indian banks & NBFCs', name: 'HDFC Bank', url: 'https://www.hdfcbank.com/personal/about-us/careers' },
  { segment: 'Indian banks & NBFCs', name: 'ICICI Bank', url: 'https://www.icicicareers.com/' },
  { segment: 'Indian banks & NBFCs', name: 'Axis Bank', url: 'https://www.axisbank.com/careers' },
  { segment: 'Indian banks & NBFCs', name: 'Kotak', url: 'https://www.kotak.com/en/about-us/careers.html' },
  { segment: 'Indian banks & NBFCs', name: 'IDFC First', url: 'https://www.idfcfirstbank.com/about-us/careers' },
  { segment: 'Indian banks & NBFCs', name: 'Bajaj Finserv', url: 'https://www.bajajfinserv.in/careers' },
  { segment: 'Indian banks & NBFCs', name: 'Tata Capital', url: 'https://www.tatacapital.com/careers.html' },
  { segment: 'Fintech', name: 'Razorpay', url: 'https://razorpay.com/jobs/' },
  { segment: 'Fintech', name: 'PhonePe', url: 'https://www.phonepe.com/careers/' },
  { segment: 'Fintech', name: 'Paytm', url: 'https://paytm.com/careers' },
  { segment: 'Fintech', name: 'CRED', url: 'https://careers.cred.club/' },
  { segment: 'Fintech', name: 'Groww', url: 'https://groww.in/careers' },
  { segment: 'Fintech', name: 'Pine Labs', url: 'https://www.pinelabs.com/careers' },
  { segment: 'AMC & broking', name: 'HDFC AMC', url: 'https://www.hdfcfund.com/about-us/careers' },
  { segment: 'AMC & broking', name: 'ICICI Pru AMC', url: 'https://www.icicipruamc.com/careers' },
  { segment: 'AMC & broking', name: 'Motilal Oswal', url: 'https://www.motilaloswalgroup.com/careers' },
  { segment: 'AMC & broking', name: 'Edelweiss', url: 'https://www.edelweissfin.com/careers' },
  { segment: 'AMC & broking', name: 'Zerodha', url: 'https://zerodha.com/careers/' },
];
